eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      #defaultZone: http://164.52.202.187:8761/eureka/
      defaultZone: http://localhost:8761/eureka/
  instance:
   hostname: localhost
    
  microservice:
  visor-master-service:
    endpoints:
      endpoint:
        uri: http://VISOR-MASTER-SERVICE/masters/
  
   

