eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost       
microservice:
  visor-prs-service:
    endpoints:
      endpoint:
        uri: http://VISOR-PRS-SERVICE/prs/
   

      

  
   

