eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost       
microservice:
  visor-prs-service:
    endpoints:
      endpoint:
        uri: http://VISOR-PRS-SERVICE/prs/
  order-service:
    endpoints:
      endpoint:
        uri: http://ORDER-SERVICE/order/bookOrder
  visor-master-service:
    endpoints:
      endpoint:
        uri: http://VISOR-MASTER-SERVICE/masters/
  visor-exams-service:
    endpoints:
      endpoint:
        uri: http://VISOR-EXAMS-SERVICE/exams/
  visor-teacherapp-service:
    endpoints:
      endpoint:
        uri: http://VISOR-TEACHERAPP-SERVICE/teachers/
   
   

      

  
   

